import json, time, urllib.parse, urllib.request
from pathlib import Path
UA='SafeLegalAI-Bot/1.0 (+https://safelegalai.com/datasets; hello@safelegalai.com)'
queries={
 'rules-ai':'("generative artificial intelligence" OR "generative AI") ("administrative order" OR "court rule" OR "court filings")',
 'upl-ai':'("unauthorized practice" OR "practice of law") (ChatGPT OR "generative AI" OR "artificial intelligence" OR DoNotPay)',
 'donotpay':'DoNotPay OR "Do Not Pay"',
 'pro-se-chatgpt':'("pro se" OR "self-represented") (ChatGPT OR "generative AI" OR "artificial intelligence" OR "AI-generated")',
 'pro-se-ai':'("self represented" OR "self-represented" OR "pro se") "artificial intelligence"',
 'criminal-ai-police':'("AI-generated" OR "artificial intelligence" OR "machine learning") ("police report" OR "police reports" OR "law enforcement")',
 'criminal-facial':'("facial recognition" OR "face recognition") ("artificial intelligence" OR algorithm OR software)',
 'criminal-sentencing':'(COMPAS OR "risk assessment" OR algorithmic OR algorithm) (sentencing OR bail OR pretrial) (Loomis OR "due process" OR defendant)',
 'shotspotter':'ShotSpotter OR "Shot Spotter" OR "gunshot detection"',
 'forensic-software':'("probabilistic genotyping" OR STRmix OR TrueAllele OR "forensic software") (algorithm OR software)',
 'ai-generated-evidence':'("AI-generated" OR "generated by AI") (criminal OR defendant OR evidence)',
 'large-language':'"large language model"',
}
outdir=Path('work/research/cl-topic')
outdir.mkdir(parents=True, exist_ok=True)
base='https://www.courtlistener.com/api/rest/v4/search/'
for i,(name,q) in enumerate(queries.items(),1):
    params={'q':q,'type':'o','filed_after':'2022-11-30','order_by':'dateFiled desc'}
    url=base+'?'+urllib.parse.urlencode(params)
    req=urllib.request.Request(url, headers={'User-Agent':UA})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data=resp.read()
        (outdir/f'{name}.json').write_bytes(data)
        j=json.loads(data)
        print(f'## {name}: count={j.get("count")} url={url}')
        for r in j.get('results',[])[:8]:
            ops=r.get('opinions') or []
            sn=' '.join(((ops[0].get('snippet') if ops else r.get('snippet')) or '').split())[:240]
            dl=ops[0].get('download_url') if ops else r.get('download_url')
            print(r.get('dateFiled'), r.get('court_id'), r.get('caseName'), r.get('docketNumber'), 'cluster', r.get('cluster_id'))
            print('  ', dl)
            print('  ', sn)
    except Exception as e:
        print(f'ERR {name}: {e}')
    if i != len(queries):
        time.sleep(13)
