import json, re, hashlib
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path('.')
FETCHED='2026-09-07T22:15:00Z'

def clean_text(s):
    s=s.replace('\u00a0',' ')
    s=re.sub(r'\s+',' ',s)
    return s.strip()

def read_dec(id):
    return clean_text((ROOT/'work/texts/decisions'/f'{id}.txt').read_text(errors='ignore'))

def read_lit(name):
    return clean_text((ROOT/'work/texts/litigation'/f'{name}.txt').read_text(errors='ignore'))

def sha_text(id):
    p=ROOT/'work/texts/decisions'/f'{id}.txt'
    if not p.exists(): return None
    return hashlib.sha256(p.read_bytes()).hexdigest()

def excerpt(id, start, end=None, maxchars=1500):
    t=read_dec(id)
    i=t.lower().find(start.lower())
    if i<0:
        raise ValueError(f'start not found {id}: {start}')
    if end:
        j=t.lower().find(end.lower(), i)
        if j<0: raise ValueError(f'end not found {id}: {end}')
        j += len(end)
    else:
        j=min(len(t), i+maxchars)
        # try to finish at a sentence boundary after 450 chars
        k=t.rfind('. ', i+300, j)
        if k>i: j=k+1
    return t[i:j].strip()

def excerpt_term(id, term, before=0, after=900):
    t=read_dec(id)
    pos=t.lower().find(term.lower())
    if pos<0: raise ValueError(f'term not found {id}: {term}')
    i=max(0,pos-before)
    if before:
        # move to previous sentence boundary if close
        b=max(t.rfind('. ', max(0,pos-before), pos), t.rfind('? ', max(0,pos-before), pos), t.rfind('! ', max(0,pos-before), pos))
        if b>max(0,pos-before)+80: i=b+2
    j=min(len(t), pos+after)
    k=max(t.rfind('. ', pos+250, j), t.rfind('? ', pos+250, j), t.rfind('! ', pos+250, j))
    if k>pos: j=k+1
    return t[i:j].strip()

# source metadata from manifest plus corrections
manifest={}
for mf in ['decision_manifest.json','decision_retry_manifest.json','okla_retry_manifest.json']:
    p=ROOT/'work/research'/mf
    if p.exists():
        for r in json.load(open(p)):
            manifest[r['id']]=r
src=lambda id: manifest.get(id,{}).get('source_url')
cl=lambda id: manifest.get(id,{}).get('courtlistener_url')
lead=lambda id: [x.strip() for x in manifest.get(id,{}).get('lead','manual').split(';') if x.strip()]

source_overrides={
 'tr-ross-2025':'https://www.ded.uscourts.gov/sites/ded/files/opinions/20-613_5.pdf',
 'kadrey-meta-2025':'https://www.govinfo.gov/content/pkg/USCOURTS-cand-3_23-cv-03417/pdf/USCOURTS-cand-3_23-cv-03417-37.pdf',
 'texas-rule-2026':'https://www.txcourts.gov/media/1462936/269054.pdf'
}

rows=[]
def add_dec(**r):
    id=r['decision_id']
    r.setdefault('court_code', manifest.get(id,{}).get('court_id'))
    r.setdefault('state', None)
    r.setdefault('citation', None)
    r.setdefault('docket_number', manifest.get(id,{}).get('docketNumber'))
    r.setdefault('ai_tool_named', None)
    r.setdefault('incident', None)
    r.setdefault('tracker_slug', None)
    r.setdefault('courtlistener_url', cl(id))
    r.setdefault('text_sha256', sha_text(id))
    r.setdefault('source_url', source_overrides.get(id) or src(id))
    r.setdefault('archive_url', None)
    r.setdefault('fetched_at', FETCHED)
    r.setdefault('verification', 'fetched-and-read')
    r.setdefault('lead_source', lead(id))
    r.setdefault('notes', None)
    rows.append(r)

add_dec(decision_id='ark-rule-115-2025',case_name='In re Amendments to the Arkansas Rules of Professional Conduct',court='Supreme Court of Arkansas',court_level='state-supreme',state='AR',date_filed='2025-06-05',citation='2025 Ark. 115',docket_number=None,document_type='opinion',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court published proposed AI-related amendments to the Arkansas Rules of Professional Conduct for comment.',ai_passage=excerpt('ark-rule-115-2025','In response to the growing use of artificial intelligence','The comment period shall end on August 1, 2025.'),cited_authorities=[],summary='The Arkansas Supreme Court publishes for comment professional-conduct amendments responding to artificial intelligence in legal practice. The per curiam order describes joint study by court and bar committees and proposes changes clarifying lawyers’ duties when using nonhuman assistance.',lead_source=['Arkansas court site search','user brief'])
add_dec(decision_id='ark-rule-117-2025',case_name='In re Creation of Arkansas Supreme Court Administrative Order No. 25. Artificial Intelligence',court='Supreme Court of Arkansas',court_level='state-supreme',state='AR',date_filed='2025-06-05',citation='2025 Ark. 117',docket_number=None,document_type='opinion',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court published proposed Administrative Order No. 25 on artificial intelligence for public comment.',ai_passage=excerpt('ark-rule-117-2025','The use of AI has become increasingly prominent.','(b) Anyone who enters confidential or sealed'),cited_authorities=[],summary='The Arkansas Supreme Court proposes Administrative Order No. 25, a court-system AI rule focused first on generative-AI use with confidential court data. The opinion invites comments while warning that lawyers, court personnel, and the public may use AI intentionally or inadvertently.',lead_source=['user brief','Arkansas court site search'])
add_dec(decision_id='ark-rule-220-2025',case_name='In re Adoption of Arkansas Supreme Court Administrative Order No. 25. Artificial Intelligence',court='Supreme Court of Arkansas',court_level='state-supreme',state='AR',date_filed='2025-12-11',citation='2025 Ark. 220',docket_number=None,document_type='opinion',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court adopted Administrative Order No. 25 on artificial intelligence effective immediately.',ai_passage=excerpt('ark-rule-220-2025','On June 5, 2025, we published for comment','A public LLM is accessible to anyone'),cited_authorities=['In re Creation of Ark. Sup. Ct. Admin. Order No. 25, 2025 Ark. 117'],summary='The Arkansas Supreme Court adopts Administrative Order No. 25 after a comment period with no substantive comments. The new order requires court participants to consider confidentiality and data-retention risks before entering court or client data into generative-AI systems.',lead_source=['Arkansas court site search','user brief'])
add_dec(decision_id='ark-rule-221-2025',case_name='In re Amendments to the Arkansas Rules of Professional Conduct',court='Supreme Court of Arkansas',court_level='state-supreme',state='AR',date_filed='2025-12-11',citation='2025 Ark. 221',docket_number=None,document_type='opinion',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court adopted AI-related amendments to the Arkansas Rules of Professional Conduct effective immediately.',ai_passage=excerpt('ark-rule-221-2025','On June 5, 2025, we published proposed amendments','generative artificial intelligence platforms.'),cited_authorities=['In re Amends. to the Ark. Rules of Prof’l Conduct, 2025 Ark. 115','Arkansas Supreme Court Administrative Order No. 25'],summary='The Arkansas Supreme Court adopts professional-conduct amendments addressing lawyers’ use of artificial intelligence and other nonhuman assistance. The amendments say AI use is not barred but does not excuse rule violations, and Rule 5.3 supervision includes generative-AI platforms.',lead_source=['Arkansas court site search'])
add_dec(decision_id='okla-rule-2026',case_name='In re Addition of a New Rule to the Rules of the Court of Criminal Appeals',court='Oklahoma Court of Criminal Appeals',court_code='oklacrimapp',court_level='state-supreme',state='OK',date_filed='2026-02-18',citation='2026 OK CR 7',docket_number='CCAD-2026-1',document_type='administrative-order',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court adopted Rule 1.17 requiring verification of generative-AI-assisted filings.',ai_passage=excerpt('okla-rule-2026','Recognizing the novel and rapid development','finding of contempt.'),cited_authorities=[],summary='The Oklahoma Court of Criminal Appeals adopts a procedural rule for generative-AI use in filings. Rule 1.17 requires parties or counsel to verify AI-generated or AI-modified content for accuracy and makes noncompliant filings subject to sanctions.',verification='mirror-read',courtlistener_url='https://www.courtlistener.com/opinion/10795792/x/',lead_source=['user brief','CourtListener anonymous search'],notes='Official OSCN endpoint timed out; court-authored public-domain text was read from CourtListener storage fallback.')
add_dec(decision_id='delaware-policy-2024',case_name='In re Interim Policy on the Use of Generative AI by Judicial Officers and Court Personnel',court='Supreme Court of Delaware',court_code=None,court_level='state-supreme',state='DE',date_filed='2024-10-21',citation=None,docket_number=None,document_type='administrative-order',topics=['rules-by-opinion','court-ai-use'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court ordered Delaware judicial officers and court personnel to follow an interim generative-AI policy.',ai_passage=excerpt('delaware-policy-2024','WHEREAS, the DCLT has recommended adoption','BY THE COURT:'),cited_authorities=[],summary='The Delaware Supreme Court adopts an interim policy governing generative-AI use by judicial officers and court personnel. The order emphasizes that GenAI may assist official work only under a policy designed to protect judicial, legal, and professional judgment.',source_url='https://courts.delaware.gov/forms/download.aspx?id=266848',lead_source=['Delaware Courts operating procedures','web search'])
add_dec(decision_id='illinois-policy-2024',case_name='Illinois Supreme Court Policy on Artificial Intelligence',court='Supreme Court of Illinois',court_code=None,court_level='state-supreme',state='IL',date_filed='2025-01-01',citation=None,docket_number=None,document_type='administrative-order',topics=['rules-by-opinion','court-ai-use'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court made an artificial-intelligence policy effective for Illinois courts on January 1, 2025.',ai_passage=excerpt('illinois-policy-2024','Embracing the advancements of artificial intelligence','Disclosure of AI use should not be required in a pleading.'),cited_authorities=[],summary='The Illinois Supreme Court policy authorizes responsible AI use by court users, lawyers, judges, and staff while stressing accuracy, bias, confidentiality, and accountability. It states that AI use should not be discouraged and generally should not require pleading disclosure.',source_url='https://ilcourtsaudio.blob.core.windows.net/antilles-resources/resources/e43964ab-8874-4b7a-be4e-63af019cb6f7/Illinois%20Supreme%20Court%20AI%20Policy.pdf',lead_source=['Illinois Courts news page'])
add_dec(decision_id='texas-rule-2026',case_name='Preliminary Approval of Amendments to Texas Rule of Civil Procedure 13 and Texas Rules of Appellate Procedure 9 and 52',court='Supreme Court of Texas',court_code=None,court_level='state-supreme',state='TX',date_filed='2026-06-26',citation='Misc. Docket No. 26-9054',docket_number='26-9054',document_type='administrative-order',topics=['rules-by-opinion'],primary_topic='rules-by-opinion',court_used_ai=False,disposition='The court preliminarily approved rule amendments addressing verification and sanctions for inaccurate filings.',ai_passage=excerpt('texas-rule-2026','Rule 13 has been rewritten to modernize','Paragraph (e)(2) imports available sanctions from Rule 215, tailoring them for filings instead of discovery.'),cited_authorities=['Texas Rule of Civil Procedure 13','Texas Rule of Civil Procedure 57','Texas Rules of Appellate Procedure 9 and 52'],summary='The Texas Supreme Court preliminarily approves amendments to civil and appellate filing rules. Comments explain that the changes address improper AI use by reinforcing attorneys’ and self-represented parties’ obligation to verify authorities, quotations, and holdings before filing.',verification='mirror-read',archive_url='https://web.archive.org/web/20260727115735/https://www.txcourts.gov/media/1462936/269054.pdf',lead_source=['Texas Judicial Branch','web search'],notes='Official PDF returned 403 to curl; official PDF was read from an existing Wayback capture.')

add_dec(decision_id='tr-ross-2025',case_name='Thomson Reuters Enterprise Centre GmbH v. ROSS Intelligence Inc.',court='U.S. District Court for the District of Delaware',court_code='ded',court_level='federal-district',state='DE',date_filed='2025-02-11',citation='765 F. Supp. 3d 382',docket_number='1:20-cv-00613-SB',document_type='memorandum-opinion',topics=['substantive-ai-law'],primary_topic='substantive-ai-law',court_used_ai=False,ai_tool_named='ROSS AI search tool',disposition='The court granted Thomson Reuters partial summary judgment and rejected ROSS’s fair-use defense.',ai_passage=excerpt('tr-ross-2025','Ross’s use is not transformative because','That makes this factor much trickier.'),cited_authorities=['Andy Warhol Found. for Visual Arts, Inc. v. Goldsmith, 598 U.S. 508 (2023)'],summary='The District of Delaware treats ROSS’s use of Westlaw headnotes as nontransformative AI training for a competing legal-research tool. The opinion grants partial summary judgment for Thomson Reuters and becomes a central legal-AI copyright ruling on appeal.',source_url='https://www.ded.uscourts.gov/sites/ded/files/opinions/20-613_5.pdf',lead_source=['user brief'])
add_dec(decision_id='bartz-anthropic-2025',case_name='Bartz v. Anthropic PBC',court='U.S. District Court for the Northern District of California',court_code='cand',court_level='federal-district',state='CA',date_filed='2025-06-23',citation=None,docket_number='3:24-cv-05417-WHA',document_type='order',topics=['substantive-ai-law'],primary_topic='substantive-ai-law',court_used_ai=False,ai_tool_named='Claude',disposition='The court ruled that training uses were fair use but preserved claims over Anthropic’s central library.',ai_passage=excerpt('bartz-anthropic-2025','An artificial intelligence firm downloaded','texts selected from a central library Anthropic had assembled.'),cited_authorities=[],summary='The Northern District of California rules on Anthropic’s book copying for Claude and related language models. Judge Alsup distinguishes training from maintaining a central library, finding transformative fair use for training while allowing claims about pirated library retention to proceed.',lead_source=['user brief'])
add_dec(decision_id='kadrey-meta-2025',case_name='Kadrey v. Meta Platforms, Inc.',court='U.S. District Court for the Northern District of California',court_code='cand',court_level='federal-district',state='CA',date_filed='2025-06-25',citation='788 F. Supp. 3d 1026',docket_number='3:23-cv-03417-VC',document_type='order',topics=['substantive-ai-law'],primary_topic='substantive-ai-law',court_used_ai=False,ai_tool_named='Llama',disposition='The court denied plaintiffs’ partial-summary-judgment motion and granted Meta’s cross-motion on fair use.',ai_passage=excerpt('kadrey-meta-2025','Companies are presently racing','This case presents the question whether such conduct is illegal.'),cited_authorities=[],summary='The Northern District of California grants Meta partial summary judgment on fair use for copying authors’ books to train Llama. The order stresses generative AI’s potential market harms while finding the plaintiffs’ record inadequate to defeat fair use in this case.',source_url='https://www.govinfo.gov/content/pkg/USCOURTS-cand-3_23-cv-03417/pdf/USCOURTS-cand-3_23-cv-03417-37.pdf',lead_source=['user brief','GovInfo search API'])
add_dec(decision_id='thaler-perlmutter-2025',case_name='Thaler v. Perlmutter',court='U.S. Court of Appeals for the D.C. Circuit',court_code='cadc',court_level='federal-appellate',state=None,date_filed='2025-03-18',citation=None,docket_number='23-5233',document_type='opinion',topics=['substantive-ai-law'],primary_topic='substantive-ai-law',court_used_ai=False,ai_tool_named='Creativity Machine',disposition='The court affirmed denial of copyright registration for a work claimed to be authored by a machine.',ai_passage=excerpt('thaler-perlmutter-2025','This case presents a question made salient','requires all eligible work to be authored in the first instance by a human being.'),cited_authorities=[],summary='The D.C. Circuit holds that the Copyright Act requires human authorship and affirms the Copyright Office’s refusal to register a work listing Thaler’s Creativity Machine as sole author. The opinion frames AI authorship as a statutory question.',lead_source=['user brief'])

add_dec(decision_id='anderegg-ca7-2026',case_name='United States v. Anderegg',court='U.S. Court of Appeals for the Seventh Circuit',court_code='ca7',court_level='federal-appellate',state=None,date_filed='2026-08-25',citation=None,docket_number='25-1354',document_type='opinion',topics=['substantive-ai-law','criminal-justice-algorithms'],primary_topic='substantive-ai-law',court_used_ai=False,ai_tool_named='Stable Diffusion',disposition='The court reversed dismissal of production and possession counts involving AI-generated CSAM and remanded.',ai_passage=excerpt('anderegg-ca7-2026','Steven Anderegg is charged with pro- ducing','denied the remainder.'),cited_authorities=['18 U.S.C. § 2258A'],summary='The Seventh Circuit addresses criminal charges alleging use of Stable Diffusion to create CSAM-like images. It analyzes how federal child-exploitation statutes apply to AI-generated depictions and reverses dismissal of key counts, making the opinion important for AI criminal-law doctrine.',lead_source=['user brief','CourtListener anonymous search'])
add_dec(decision_id='joyner-dcd-2026',case_name='United States v. Joyner',court='U.S. District Court for the District of Columbia',court_code='dcd',court_level='federal-district',state='DC',date_filed='2026-06-19',citation=None,docket_number='Criminal No. 2023-0309',document_type='memorandum-opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='STRmix',disposition='The court granted in part and denied in part several limine motions, including challenges to STRmix DNA evidence.',ai_passage=excerpt('joyner-dcd-2026','These samples were imported into a probabilistic genotyping software, STRmix','STRmix ultimately assigned Items 4, 44, 56(1), and 69 likelihood ratios of 10, 21, 100, and 34, respectively.'),cited_authorities=['Federal Rule of Evidence 702','Daubert v. Merrell Dow Pharmaceuticals, Inc., 509 U.S. 579 (1993)'],summary='The D.C. district court evaluates STRmix probabilistic-genotyping evidence among extensive pretrial motions in a robbery and carjacking prosecution. The opinion explains the software’s likelihood ratios and rules on admissibility limits for DNA testimony.',verification='mirror-read',notes='D.D.C. public-document CGI path is disallowed by robots.txt; court-authored PDF was read from CourtListener storage fallback.')
add_dec(decision_id='booker-ohio-2026',case_name='State v. Booker',court='Ohio Court of Appeals, First Appellate District',court_code='ohioctapp',court_level='state-appellate',state='OH',date_filed='2026-08-28',citation='2026-Ohio-3371',docket_number='C-250699',document_type='opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='ShotSpotter',disposition='The court affirmed denial of suppression and affirmed Booker’s conviction.',ai_passage=excerpt('booker-ohio-2026','The Cincinnati Police Department deploys surveillance technology','open-air drug market.'),cited_authorities=[],summary='The Ohio appellate court considers a suppression challenge arising from ShotSpotter and real-time crime-center surveillance. It describes how police used automated gunshot detection and video to locate suspects before affirming the search and conviction.',lead_source=['CourtListener anonymous search shotspotter.json'])
add_dec(decision_id='aguilera-ca9-2026',case_name='United States v. Aguilera',court='U.S. Court of Appeals for the Ninth Circuit',court_code='ca9',court_level='federal-appellate',state=None,date_filed='2026-08-24',citation=None,docket_number='25-3366',document_type='opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='ShotSpotter',disposition='The court affirmed Aguilera’s conviction, vacated his sentence, and remanded for resentencing.',ai_passage=excerpt('aguilera-ca9-2026','ShotSpotter is a service that detects gunshots','Officers Hurtado and Frisk saw a person walking away in that direction'),cited_authorities=[],summary='The Ninth Circuit reviews a San Francisco ammunition conviction involving ShotSpotter alerts and witness reports. The opinion affirms suppression rulings tied to the initial police response while vacating the sentence for unrelated sentencing reasons.',lead_source=['CourtListener anonymous search shotspotter.json'])
add_dec(decision_id='wright-ny-2026',case_name='People v. Wright',court='New York Supreme Court, Appellate Division, Fourth Department',court_code='nyappdiv',court_level='state-appellate',state='NY',date_filed='2026-07-24',citation='2026 NY Slip Op 04580',docket_number='299 KA 23-00567',document_type='opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='ShotSpotter',disposition='The court affirmed the weapon-possession judgment and upheld the suppression ruling.',ai_passage=excerpt('wright-ny-2026','at around 4:30 a.m. on the day in question','causing the police to chase after him in pursuit.'),cited_authorities=['People v. Thomas, 34 N.Y.3d 545 (2019)'],summary='The New York appellate court affirms a suppression ruling where officers heard a gunshot and then received a ShotSpotter activation. The opinion treats the activation as corroboration supporting reasonable suspicion for the ensuing pursuit and firearm recovery.',verification='mirror-read',notes='Official New York reporter page was not reliably downloadable; text was read from CourtListener storage fallback.')
add_dec(decision_id='figueroa-hernandez-fl-2026',case_name='Figueroa Hernandez v. State',court='Florida Third District Court of Appeal',court_code='fladistctapp',court_level='state-appellate',state='FL',date_filed='2026-07-22',citation=None,docket_number='3D2024-1368',document_type='opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='STRmix',disposition='The court affirmed the conviction and rejected challenges to DNA evidence and other trial rulings.',ai_passage=excerpt('figueroa-hernandez-fl-2026','Cosette Alvarez of the Miami-Dade Police Department’s crime lab','denied both motions.'),cited_authorities=['Daubert','Kemp v. State, 280 So. 3d 81 (Fla. 4th DCA 2019)'],summary='The Florida appellate court discusses expert testimony comparing manual DNA interpretation with STRmix probabilistic genotyping. The court affirms after reviewing a Daubert hearing and the defense argument that newer software better suited mixed, low-level DNA profiles.',lead_source=['CourtListener anonymous search forensic-software.json'])
add_dec(decision_id='guerra-ny-2026',case_name='People v. Guerra',court='New York Court of Appeals',court_code='ny',court_level='state-supreme',state='NY',date_filed='2026-06-18',citation='2026 NY Slip Op 03905',docket_number='62',document_type='opinion',topics=['criminal-justice-algorithms'],primary_topic='criminal-justice-algorithms',court_used_ai=False,ai_tool_named='forensic software program',disposition='The court affirmed the Appellate Division’s order granting a new trial for ineffective assistance.',ai_passage=excerpt('guerra-ny-2026','In January 2017, an NYPD detective ran a forensic software program','No USB drive was recovered from the building.'),cited_authorities=[],summary='The New York Court of Appeals describes forensic software used to identify peer-to-peer CSAM sharing and later computer-forensics evidence. The court’s ineffective-assistance analysis turns on stipulations about digital evidence, possession, and mens rea.',verification='mirror-read',notes='Read from CourtListener storage copy of New York reporter HTML after official site access issues.')

add_dec(decision_id='sherwin-iowa-2026',case_name='Sherwin v. State of Iowa, Department of Criminal Investigation',court='Iowa Court of Appeals',court_code='iowactapp',court_level='state-appellate',state='IA',date_filed='2026-07-22',citation=None,docket_number='25-0992',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='Chat GPT',disposition='The court affirmed dismissal and rejected the pro se litigants’ request to require AI-use certification by defendants.',ai_passage=excerpt('sherwin-iowa-2026','the district court properly denied the Sherwins’ request','refusing to require the defendants to disclose any use of artificial intelligence.'),cited_authorities=['Luke v. Iowa Dep’t of Health & Human Services, 29 N.W.3d 635 (Iowa Ct. App. 2025)'],summary='The Iowa Court of Appeals rejects self-represented plaintiffs’ attempt to strike opposing motions because defendants did not certify whether they used ChatGPT or other AI. The court says no disclosure rule was shown and AI-assisted research or drafting is not inherently improper.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='webb-indiana-tax-2026',case_name='Webb v. Sullivan County Assessor',court='Indiana Tax Court',court_code='indtc',court_level='state-specialty' if False else 'other',state='IN',date_filed='2026-07-16',citation=None,docket_number='25T-TA-00029',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='generative AI',disposition='The court denied the pro se taxpayers’ motion to supplement the record and warned about AI citation accuracy.',ai_passage=excerpt('webb-indiana-tax-2026','The Webbs refer to various court rules','and accurate.'),cited_authorities=['Williams v. Kirch, 268 N.E.3d 284 (Ind. Ct. App. 2025)','Wilcox v. Gingrinch, 274 N.E.3d 1269 (Ind. Ct. App. 2026)','Sanders v. United States, 176 Fed. Cl. 163 (Fed. Cl. 2025)'],summary='The Indiana Tax Court suspects self-represented taxpayers used generative AI in a motion citing real rules for incorrect propositions. The court recognizes benefits for self-represented parties but warns that all litigants must verify sources and holdings.',verification='mirror-read',notes='Official Indiana API was discovered; court-authored PDF was read from CourtListener storage fallback after direct retrieval issues.')
add_dec(decision_id='davis-ohio-2026',case_name='State v. Davis',court='Ohio Court of Appeals, Seventh Appellate District',court_code='ohioctapp',court_level='state-appellate',state='OH',date_filed='2026-08-03',citation='2026-Ohio-2993',docket_number='25 CO 0050',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='generative Artificial Intelligence (AI)',disposition='The court affirmed Davis’s conviction and held him to appellate briefing requirements despite disclosed AI use.',ai_passage=excerpt('davis-ohio-2026','Appellant has also notified this Court','does not excuse him.'),cited_authorities=['State ex rel. Neil v. French, 2018-Ohio-2692'],summary='The Ohio appellate court addresses a self-represented criminal appellant who disclosed using generative AI to create an overlength brief. It holds that AI use and pro se status do not shift the burden to the court to validate arguments or excuse rule violations.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='in-re-ap-ohio-2026',case_name='In re A.P.',court='Ohio Court of Appeals, Twelfth Appellate District',court_code='ohioctapp',court_level='state-appellate',state='OH',date_filed='2026-07-27',citation='2026-Ohio-2862',docket_number='CA2025-12-011',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='artificial intelligence',disposition='The court affirmed and warned that erroneous AI-assisted citations may be disregarded or sanctioned.',ai_passage=excerpt('in-re-ap-ohio-2026','Before we consider Father\'s assignments of error','other litigants.'),cited_authorities=['Chasteen v. Lynch, 2024-Ohio-5857','Ohio Appellate Rule 16(A)(7)'],summary='The Ohio appellate court pauses before the merits to address a father’s acknowledged AI-assisted brief. The court identifies erroneous citations, reminds parties that false authorities may lead to sanctions, and applies ordinary appellate standards to the self-represented parent.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='lampinen-ohio-2026',case_name='Lampinen v. Borer',court='Ohio Court of Appeals, Eleventh Appellate District',court_code='ohioctapp',court_level='state-appellate',state='OH',date_filed='2026-07-20',citation='2026-Ohio-2769',docket_number='2025-L-134',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='artificial intelligence tools',disposition='The court affirmed dismissal and declined to impose sanctions while cautioning all litigants.',ai_passage=excerpt('lampinen-ohio-2026','Such a practice is suggestive','may lead to sanctions.'),cited_authorities=['State v. Coleman, 2026-Ohio-965','Chambers v. NASCO, Inc., 501 U.S. 32 (1991)'],summary='The Ohio appellate court sees signs that a self-represented brief relied improperly on AI tools, but it declines sanctions. The court cautions that lack of candor may be sanctionable and refuses to construct arguments for the appellant.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='mathis-fl-2026',case_name='Mathis v. Mathis',court='Florida Fourth District Court of Appeal',court_code='fladistctapp',court_level='state-appellate',state='FL',date_filed='2026-07-29',citation=None,docket_number='4D2025-2986',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='artificial intelligence',disposition='The court reversed and remanded a child-support order while disregarding phantom authorities in a pro se brief.',ai_passage=excerpt('mathis-fl-2026','In his answer brief, the husband cites two cases','Those who use artificial intelligence to assist in these submissions must ensure their accuracy.'),cited_authorities=['Friend v. Serpa, 425 So. 3d 51 (Fla. 4th DCA 2025)'],summary='The Florida appellate court notes that a self-represented appellee cited two nonexistent cases. Without imposing sanctions, it disregards the phantom authority and reiterates that attorneys and pro se litigants remain responsible for verifying AI-assisted filings.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='mitchell-ga-2026',case_name='Mitchell v. HIG Realty Credit Fund, LP',court='Court of Appeals of Georgia',court_code='gactapp',court_level='state-appellate',state='GA',date_filed='2026-08-19',citation=None,docket_number='A26A0854',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='generative AI',disposition='The court affirmed summary judgment and declined sanctions while cautioning Mitchell about future AI-related citation defects.',ai_passage=excerpt('mitchell-ga-2026','As an initial matter, we note that in his appellate briefing','See Shahid v. Essam, 376 Ga. App. 145, 145–50(1) (918 SE2d 198) (2025).'),cited_authorities=['Slay v. Ross, 379 Ga. App. 1 (2026)','Shahid v. Essam, 376 Ga. App. 145 (2025)'],summary='The Georgia Court of Appeals flags fictitious and irrelevant cases in a self-represented appellant’s briefing as suggestive of unchecked generative AI. It declines sanctions because the appellee was not hampered, but warns future filings may be sanctioned.',verification='mirror-read',notes='Official Georgia e-filing download was blocked; court-authored PDF was read from CourtListener storage fallback.')
add_dec(decision_id='pangelinan-guam-2026',case_name='In re Estate of Pangelinan',court='Supreme Court of Guam',court_code='guam',court_level='state-supreme',state='GU',date_filed='2026-07-15',citation='2026 Guam 5',docket_number='CVA25-007',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='generative artificial intelligence',disposition='The court affirmed in part and reversed in part while declining sanctions for two possible AI-attributed citations.',ai_passage=excerpt('pangelinan-guam-2026','In Schacher’s opening brief, two nonexistent citations','Re: Adoption of the Judiciary of Guam Policy on Artificial Intelligence, ADM25-001, Ex. A (Admin. Order No. ADM25-001, Apr. 30, 2025).'),cited_authorities=['Re: Adoption of the Judiciary of Guam Policy on Artificial Intelligence, ADM25-001'],summary='The Supreme Court of Guam observes that two nonexistent citations in a self-represented probate appellant’s brief may be attributable to generative AI. Considering pro se status and a first appearance, it finds sanctions unwarranted but reiterates final-submission duties.',lead_source=['CourtListener anonymous search pro-se-ai.json'])
add_dec(decision_id='unger-fl-2026',case_name='Unger v. Unger',court='Florida Fourth District Court of Appeal',court_code='fladistctapp',court_level='state-appellate',state='FL',date_filed='2026-08-26',citation=None,docket_number='4D2025-2209',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='artificial intelligence',disposition='The court affirmed in part, reversed in part, remanded, and repeated a warning about AI use in filings.',ai_passage=excerpt('unger-fl-2026','We disagree with the former husband’s proposed remedy.','Affirmed in part, reversed in part, and remanded with instructions.'),cited_authorities=[],summary='The Florida appellate court repeats a prior warning to a self-represented former husband after striking his initial brief with leave to amend. The opinion cautions him about using artificial intelligence in documents filed with the court while resolving contempt issues.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'],verification='mirror-read',notes='Court-authored PDF read from CourtListener storage fallback after direct Florida media retrieval did not persist in retry metadata.')
add_dec(decision_id='monson-iowa-2026',case_name='In re the Marriage of Monson',court='Iowa Court of Appeals',court_code='iowactapp',court_level='state-appellate',state='IA',date_filed='2026-09-02',citation=None,docket_number='25-1029',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='artificial intelligence tool',disposition='The court affirmed the dissolution decree and warned that inaccurate AI-assisted appellate filings waste resources.',ai_passage=excerpt('monson-iowa-2026','During our review of Caroline’s appellate briefing','Submitting inaccurate appellate filings wastes party and judicial resources, hinders the filer’s ability to successfully advocate, and ultimately slows down the process of resolving the appeal.'),cited_authorities=['Luke v. Iowa Dep’t of Health & Human Services, 29 N.W.3d 635 (Iowa Ct. App. 2025)','Locher & Davis, PLC v. Ruth F. Woller Revocable Trust, 2024 WL 4761531 (Iowa Ct. App. Nov. 13, 2024)'],summary='The Iowa Court of Appeals identifies likely AI misuse in a self-represented divorce appellant’s brief, including nonexistent and mischaracterized authorities. The court still considers discernible claims, affirms the decree, and warns that inaccurate AI-assisted filings waste resources.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])
add_dec(decision_id='wilkinson-iowa-2026',case_name='Wilkinson v. Schmelzer',court='Iowa Court of Appeals',court_code='iowactapp',court_level='state-appellate',state='IA',date_filed='2026-08-19',citation=None,docket_number='25-0799',document_type='opinion',topics=['pro-se-ai-use'],primary_topic='pro-se-ai-use',court_used_ai=False,ai_tool_named='generative AI',disposition='The court affirmed, declined AI-use sanctions, and awarded appellate attorney fees on ordinary prevailing-party grounds.',ai_passage=excerpt('wilkinson-iowa-2026','In her resistance to Brett’s motion for remand','Thus, we decline to apply sanctions for Brett’s purported use of AI.'),cited_authorities=['Luke v. Dep’t of Health & Human Services, 2025 WL 2237311 (Iowa Ct. App. Aug. 6, 2025)'],summary='The Iowa Court of Appeals declines sanctions for a self-represented litigant’s purported generative-AI use because no hallucinated case appears and a nonexistent rule citation might be a typo. The court separately awards attorney fees based on ordinary appellate factors.',lead_source=['CourtListener anonymous search pro-se-chatgpt.json'])

# schema does not include state-specialty; Indiana Tax Court is best captured as other.
# Remove any fabricated-citations-only rows by construction.

# litigation rows
lit=[]
def add_lit(**r):
    r.setdefault('archive_url', None)
    r.setdefault('fetched_at', FETCHED)
    r.setdefault('notes', None)
    lit.append(r)

add_lit(case_id='thomson-reuters-v-ross',caption='Thomson Reuters Enterprise Centre GmbH and West Publishing Corp. v. ROSS Intelligence Inc.',court='U.S. District Court for the District of Delaware; U.S. Court of Appeals for the Third Circuit',docket_number='D. Del. 1:20-cv-00613-SB; 3d Cir. No. 25-2153',filed='2020-05-06',country='US',parties_legal_ai=['ROSS Intelligence Inc.'],qualifier='copyright-training',status='on-appeal',status_text='District-court summary judgment issued February 11, 2025; Third Circuit No. 25-2153 was argued June 11, 2026 and no opinion was found as of 2026-09-07.',milestones=[{'date':'2025-02-11','event':'Memorandum opinion granted Thomson Reuters partial summary judgment and rejected ROSS’s fair-use defense.','url':'https://www.ded.uscourts.gov/sites/ded/files/opinions/20-613_5.pdf'},{'date':'2026-06-11','event':'Third Circuit heard argument in No. 25-2153; decision pending.','url':'https://www.ca3.uscourts.gov/opinions-and-oral-arguments'}],summary='ROSS, an AI legal-research startup, used Westlaw-derived legal Q&A materials to train a competing search tool. The district court found key Westlaw material protectable and rejected fair use; the interlocutory appeal is pending in the Third Circuit.',next_expected='Third Circuit opinion in No. 25-2153.',source_url='https://www.ded.uscourts.gov/sites/ded/files/opinions/20-613_5.pdf',verification='fetched-and-read',lead_source=['user brief','Third Circuit opinions search'])
add_lit(case_id='west-publishing-v-legalease',caption='West Publishing Corporation v. LegalEase Solutions, LLC',court='U.S. District Court for the District of Minnesota',docket_number='0:18-cv-01445-DSD-ECW',filed='2018-05-24',country='US',parties_legal_ai=['LegalEase Solutions, LLC'],qualifier='copyright-training',status='judgment',status_text='Consent judgment and stipulated permanent injunction entered May 5, 2020; case closed.',milestones=[{'date':'2020-05-05','event':'Consent judgment and stipulated permanent injunction entered against LegalEase.','url':'https://ecf.mnd.uscourts.gov/cgi-bin/show_public_doc?2018cv1445-119'}],summary='West sued LegalEase over use of Westlaw content later relevant to ROSS training data. The consent judgment permanently enjoins LegalEase from using Westlaw content, sharing credentials, or using bots and automated processes to bulk copy or distribute Westlaw material.',next_expected=None,source_url='https://ecf.mnd.uscourts.gov/cgi-bin/show_public_doc?2018cv1445-119',verification='mirror-read',lead_source=['user brief','DocketAlarm mirror'],notes='Official PACER document was not freely retrieved; the court-filed consent judgment was read from a public DocketAlarm PDF mirror.')
add_lit(case_id='ftc-in-re-donotpay',caption='In the Matter of DoNotPay, Inc.',court='Federal Trade Commission',docket_number='Docket No. C-4812; File No. 232-3042',filed='2024-09-25',country='US',parties_legal_ai=['DoNotPay, Inc.'],qualifier='regulator-consumer',status='consent-order',status_text='FTC final decision and order issued January 14, 2025; DoNotPay owes monetary relief and must comply with notice, substantiation, reporting, and recordkeeping terms.',milestones=[{'date':'2024-09-30','event':'Federal Register published analysis of proposed consent order for public comment.','url':'https://www.govinfo.gov/content/pkg/FR-2024-09-30/pdf/2024-22400.pdf'},{'date':'2025-01-14','event':'FTC issued final decision and order in Docket C-4812.','url':'https://www.ftc.gov/system/files/ftc_gov/pdf/2323042_donotpay_decision_and_order_0.pdf'}],summary='The FTC challenged DoNotPay’s “robot lawyer” and AI-lawyer claims as deceptive. The final order bars unsupported claims that its service acts like a lawyer or other professional, imposes $193,000 in monetary relief, and requires customer notice and compliance reporting.',next_expected='Compliance reports and customer-notice obligations under the final order.',source_url='https://www.ftc.gov/system/files/ftc_gov/pdf/2323042_donotpay_decision_and_order_0.pdf',verification='fetched-and-read',lead_source=['user brief','Federal Register API','FTC website'])
add_lit(case_id='faridian-v-donotpay',caption='Jonathan Faridian v. DoNotPay, Inc.',court='U.S. District Court for the Northern District of California',docket_number='3:23-cv-01692-RFL',filed='2023-04-07',country='US',parties_legal_ai=['DoNotPay, Inc.'],qualifier='upl-consumer',status='dismissed',status_text='Public docket leads report a stipulated dismissal with prejudice on July 30, 2024; free final dismissal paper was not located.',milestones=[{'date':'2023-04-07','event':'Removed/filed consumer class action against DoNotPay in N.D. Cal.','url':'https://www.govinfo.gov/app/details/USCOURTS-cand-3_23-cv-01692'},{'date':'2024-01-30','event':'Court ordered jurisdictional discovery and related sealing response.','url':'https://www.govinfo.gov/content/pkg/USCOURTS-cand-3_23-cv-01692/pdf/USCOURTS-cand-3_23-cv-01692-0.pdf'},{'date':'2024-07-30','event':'Docket lead reports stipulated dismissal with prejudice.','url':None}],summary='Faridian sued DoNotPay over alleged automated legal-service representations and consumer-facing products. Free filings show arbitration and jurisdictional-discovery activity; public docket leads indicate the parties later stipulated to dismiss the federal action with prejudice in July 2024.',next_expected=None,source_url='https://www.govinfo.gov/content/pkg/USCOURTS-cand-3_23-cv-01692/pdf/USCOURTS-cand-3_23-cv-01692-0.pdf',verification='fetched-and-read',lead_source=['user brief','GovInfo','public docket leads'],notes='Final dismissal document was not found in free GovInfo/RECAP materials; status relies on public docket lead and is flagged for human review.')
add_lit(case_id='millerking-v-donotpay',caption='MillerKing, LLC v. DoNotPay, Inc.',court='U.S. District Court for the Southern District of Illinois',docket_number='3:23-cv-00863-NJR',filed='2023-03-15',country='US',parties_legal_ai=['DoNotPay, Inc.'],qualifier='upl-consumer',status='dismissed',status_text='Complaint was dismissed for lack of Article III standing; a November 28, 2023 order clarified any dismissal would be without prejudice, and no Seventh Circuit appeal was found.',milestones=[{'date':'2023-03-15','event':'Class complaint filed alleging DoNotPay’s robot-lawyer service constituted unauthorized practice and false advertising.','url':None},{'date':'2023-11-28','event':'Court amended dismissal order to clarify lack-of-standing dismissal would be without prejudice absent amendment.','url':'https://www.govinfo.gov/content/pkg/USCOURTS-ilsd-3_23-cv-00863/pdf/USCOURTS-ilsd-3_23-cv-00863-0.pdf'}],summary='MillerKing, an Illinois law firm, sued DoNotPay over “robot lawyer” marketing and alleged unauthorized practice of law. The court dismissed for lack of standing and later corrected the dismissal posture; no free record of a Seventh Circuit appeal was found.',next_expected=None,source_url='https://www.govinfo.gov/content/pkg/USCOURTS-ilsd-3_23-cv-00863/pdf/USCOURTS-ilsd-3_23-cv-00863-0.pdf',verification='fetched-and-read',lead_source=['user brief','GovInfo','public docket search'])
add_lit(case_id='evenup-v-butler-labs',caption='EvenUp, Inc. v. Butler Labs, Inc.',court='U.S. District Court for the Northern District of California',docket_number='4:25-cv-08199-YGR',filed='2025-09-26',country='US',parties_legal_ai=['EvenUp, Inc.','Butler Labs, Inc.'],qualifier='trade-secret-vendor',status='active',status_text='Docket leads report Judge Yvonne Gonzalez Rogers denied EvenUp’s preliminary-injunction motion on March 19, 2026; no free court PDF was located.',milestones=[{'date':'2025-09-26','event':'EvenUp filed trade-secret action against Butler Labs.','url':'https://ecf.cand.uscourts.gov/'},{'date':'2026-03-19','event':'Public docket lead reports order denying preliminary injunction and resolving sealing motions.','url':None}],summary='EvenUp’s trade-secret suit against Butler Labs concerns competing legal-AI products for injury and claims work. Free discovery located only docket leads, not the preliminary-injunction order; the matter appears active after a March 2026 denial of interim relief.',next_expected='Monitor N.D. Cal. docket or RECAP for free availability of the PI order and subsequent merits schedule.',source_url='https://ecf.cand.uscourts.gov/',verification='link-only',lead_source=['user brief','web search','CourtListener RECAP search throttled'],notes='CourtListener RECAP was throttled and N.D. Cal. public-document probes did not locate a free PDF; row needs human docket review.')
add_lit(case_id='canlii-v-caseway-ai',caption='Canadian Legal Information Institute v. Caseway AI',court='Supreme Court of British Columbia',docket_number='VLC-S-S-247574',filed='2024-12',country='CA',parties_legal_ai=['Caseway AI'],qualifier='database-terms',status='settled',status_text='CanLII and Caseway announced on March 20, 2026 that all matters in VLC-S-S-247574 were fully and finally resolved on confidential terms.',milestones=[{'date':'2026-03-20','event':'CanLII announced confidential settlement and final resolution of the BCSC proceeding.','url':'https://blog.canlii.org/2026/03/20/announcement-regarding-settlement-between-canlii-and-caseway/'}],summary='CanLII’s British Columbia proceeding against Caseway AI concerned alleged legal-database misuse by a legal-AI product. The parties announced a confidential settlement in March 2026, stating that both organizations would move forward independently and make no further public comment.',next_expected=None,source_url='https://justice.gov.bc.ca/cso/',verification='link-only',lead_source=['user brief','CanLII blog'],notes='No public court order was located; official BC Court Services Online is the registry source, while CanLII’s public settlement statement was read only as a lead. Needs human registry verification.')
add_lit(case_id='dalloz-v-forseti-doctrine',caption='Éditions Dalloz, Lexbase, LexisNexis, Lextenso, Lamy Liaisons v. Forseti (Doctrine)',court='Cour d’appel de Paris, Pôle 5, Chambre 1',docket_number='RG No. 23/06063',filed='2018-10',country='FR',parties_legal_ai=['Forseti','Doctrine.fr'],qualifier='database-terms',status='judgment',status_text='Paris Court of Appeal judgment dated May 7, 2025 found unfair competition and awarded damages to legal publishers; official court page was blocked to automated access.',milestones=[{'date':'2025-05-07','event':'Paris Court of Appeal issued judgment in RG No. 23/06063 concerning Doctrine.fr’s case-law collection practices.','url':'https://www.courdecassation.fr/decision/681c3dea1ca45fa20a739723'}],summary='French legal publishers challenged Forseti’s Doctrine.fr case-law collection practices. Public legal reporting and the official decision listing identify a May 2025 Paris Court of Appeal judgment finding unfair competition based on large-scale illicit collection of court decisions.',next_expected=None,source_url='https://www.courdecassation.fr/decision/681c3dea1ca45fa20a739723',verification='link-only',lead_source=['user brief','Cour de cassation link','Legalis article'],notes='Official Cour de cassation page blocked automated access; Legalis article was read for public details, so this row needs human verification against the official judgment text.')
add_lit(case_id='smartlaw-bgh-2021',caption='Hanseatische Rechtsanwaltskammer Hamburg v. Wolters Kluwer Deutschland GmbH (smartlaw)',court='Bundesgerichtshof',docket_number='I ZR 113/20',filed='2021-09-09',country='DE',parties_legal_ai=['Wolters Kluwer smartlaw'],qualifier='upl-consumer',status='judgment',status_text='BGH judgment issued September 9, 2021 affirmed dismissal of the bar chamber’s challenge and held the smartlaw document generator was not an RDG legal service.',milestones=[{'date':'2021-09-09','event':'BGH held smartlaw-style digital contract generation is not a legal service under RDG § 2(1).','url':'https://www.bundesgerichtshof.de/SharedDocs/Entscheidungen/DE/Zivilsenate/I_ZS/2020/I_ZR_113-20.pdf?__blob=publicationFile&v=1'}],summary='The German Federal Court of Justice ruled that smartlaw’s rule-based contract document generator does not provide an unauthorized legal service under the Rechtsdienstleistungsgesetz. The row is marked legal-AI-adjacent because the product is rule-based rather than generative AI.',next_expected=None,source_url='https://www.bundesgerichtshof.de/SharedDocs/Entscheidungen/DE/Zivilsenate/I_ZS/2020/I_ZR_113-20.pdf?__blob=publicationFile&v=1',verification='fetched-and-read',lead_source=['user brief','BGH official site'],notes='Rule-based document generator, included because the brief requested it with qualifier upl-consumer.')

# Fix Indiana court level after construction safety check
for r in rows:
    if r['decision_id']=='webb-indiana-tax-2026': r['court_level']='other'

# validate quick constraints before writing
ids=[r['decision_id'] for r in rows]
assert len(ids)==len(set(ids)), 'duplicate decisions'
for r in rows:
    if r['topics']==['fabricated-citations'] or r['primary_topic']=='fabricated-citations':
        raise AssertionError('forbidden fabricated-only row '+r['decision_id'])
    assert 40 <= len(r['ai_passage']) <= 4000, (r['decision_id'], len(r['ai_passage']))
    assert r.get('source_url'), r['decision_id']

Path('work/agents').mkdir(parents=True, exist_ok=True)
with open('work/agents/decisions-topics-b.jsonl','w') as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False, sort_keys=False)+'\n')
with open('work/agents/litigation-a.jsonl','w') as f:
    for r in lit:
        f.write(json.dumps(r, ensure_ascii=False, sort_keys=False)+'\n')
print('decisions',len(rows),'litigation',len(lit))
