import json, re, textwrap
from pathlib import Path
leads=json.load(open('work/leads/t1-slice-6.json'))
rows=[json.loads(l) for l in open('work/agents/decisions-t1-s6.jsonl') if l.strip()]
lead_url={}
for i,l in enumerate(leads,1):
    src=(l.get('Source') or '').strip()
    if src: lead_url[src if src.startswith('http') else 'https://www.damiencharlotin.com'+src]=i
idx_for=[lead_url[r['source_url']] for r in rows]

COURT_FIX={
 7:('Superior Court of Pennsylvania','pasuperct','state-appellate','PA','pasuperct'),
 10:('Rhode Island Superior Court','risuperct','state-trial','RI','risuperct'),
 42:('United States District Court for the Western District of Washington','wawd','federal-district','WA','wawd'),
 43:('United States District Court for the Western District of Washington','wawd','federal-district','WA','wawd'),
 80:('United States District Court for the Southern District of Florida','flsd','federal-district','FL','flsd'),
 91:('Superior Court of California, Los Angeles County','calsuperct','state-trial','CA','calsuperct'),
 99:('United States District Court for the Western District of Washington','wawd','federal-district','WA','wawd'),
 101:('United States District Court for the Southern District of Florida','flsd','federal-district','FL','flsd'),
}
DISP={
 2:"The court denied the stay motion, granted CBS's motion to dismiss without leave to amend, and terminated the case.",
 7:"The court affirmed the order dismissing the custody petition with prejudice and did not rely on the defective authorities.",
 10:"The court remanded the zoning appeal to the board for a continued public hearing and cautioned counsel about likely AI-generated citations.",
 39:"The court dismissed the appeal under ARCAP 25 and awarded appellee reasonable attorney fees and costs for repeated fabricated citations.",
 41:"The court granted defendants' motion to dismiss, dismissed the complaint without prejudice, and reminded the plaintiff that false authorities may draw Rule 11 sanctions.",
 46:"The court denied the debtor's Rule 60 motions after noting an inaccurate or nonexistent Whittaker citation in the debtor's papers.",
 47:"The court affirmed dismissal of the contract claims with prejudice and noted counsel's AI-based erroneous citations and false quotations.",
 49:"The court adopted the report and recommendation, dismissed the amended complaint with prejudice, and entered a filing injunction.",
 50:"The court adopted the report and recommendation, granted defendants' motions to dismiss, and dismissed the action with prejudice.",
 57:"The magistrate judge recommended granting Quikrete summary judgment and denying plaintiffs' summary-judgment motion despite the hallucinated quotation.",
 59:"The court dismissed the appeal with prejudice as a Rule 11 sanction for repeated fictitious AI-generated citations.",
 64:"The court granted Nelnet's motion to dismiss, denied the plaintiff's motions, and dismissed the case without prejudice.",
 75:"The court dismissed the complaint without leave to amend, denied the temporary-restraining-order motion, and dismissed the action without prejudice.",
 80:"The magistrate judge recommended denying the renewed preliminary-injunction motion and warned that further false AI citations could require a sanctions hearing.",
 86:"The court denied the temporary-restraining-order motion and warned the self-represented plaintiff against further inaccurate or incomplete citations.",
 92:"The court denied the motion to dismiss, granted judicial notice, and ordered defense counsel to produce authorities or explain why sanctions should not issue.",
 94:"The court granted the motion to dismiss, entered judgment for American Airlines, and did not impose sanctions after the plaintiff withdrew the fictitious citation.",
 99:"The court granted the motions to dismiss and for judgment on the pleadings, struck improper notices, and dismissed all claims with prejudice.",
 101:"The magistrate judge recommended granting discovery sanctions in part and noted defendants corrected AI hallucinations after the court flagged them.",
 108:"The court granted the dismissal motions and judicial-notice request, dismissed the complaint without prejudice, and allowed an amended complaint.",
}
COND={
 1:"The self-represented party's opposition cited Lewis v. City of Trenton, 2020 WL 6204330, a case the court found did not exist.",
 8:"The self-represented party's opposition used hallucinogenic citations to nonexistent cases while opposing dismissal motions.",
 39:"The self-represented party's appellate briefs contained 25 made-up or substantially erroneous citations, including fake quotes and unsupported propositions.",
 42:"Counsel's opening brief included erroneous citations generated by AI-based search engines, combining captions, unrelated citations, and unsupported principles.",
 50:"The self-represented party's objection cited United States v. Lopez, 817 F.3d 541, 545 (5th Cir. 2016), which the court described as a phantom case.",
 57:"Counsel's summary-judgment briefing misrepresented Ash v. Flowers Foods and used hallucinated quotations that do not appear in that opinion.",
 64:"The self-represented party's motions cited several cases that Nelnet said did not exist; the party admitted the citations were incorrect and filed no correction.",
 75:"Counsel's temporary-restraining-order motion cited nonexistent cases and inaccurate quotations while seeking to halt a state unlawful-detainer proceeding.",
 80:"The self-represented parties' reply misread Holden and cited a nonexistent page beyond the end of the Eleventh Circuit opinion.",
 86:"The self-represented party's motion quoted language not found in Zschernig and gave incomplete citations to Hartman, Estelle, and Glucksberg.",
 92:"Defense counsel attributed a quotation to Headley that the court could not locate and cited Dann for a proposition the court could not find.",
 94:"The self-represented party's opposition cited a fictitious case, then withdrew the citation after the defendant requested dismissal as a sanction.",
 101:"Defense counsel's sanctions response included apparent AI hallucinations, later corrected after the court notified counsel of the problem.",
 108:"The self-represented party's response cited McGinnis v. GMAC Mortgage for propositions the court found fabricated or hallucinated.",
}

def clean(s): return re.sub(r'\s+',' ',(s or '').strip())
def sentence(s):
    s=clean(s).strip(' ;,')
    if s and s[-1] not in '.!?': s+='.'
    return s[0].upper()+s[1:] if s else s

def short_court(c):
    for a,b in [('United States District Court for the ',''),('United States Court of Appeals for the ',''),('Court of Appeals of Washington','Washington Court of Appeals'),('Court of Appeals of Arizona','Arizona Court of Appeals'),('Appellate Court of Illinois','Illinois Appellate Court'),('District Court of Appeal of Florida','Florida District Court of Appeal')]:
        c=c.replace(a,b)
    return c

def prefix_id(old,newprefix):
    m=re.match(r'^[a-z0-9]+-2026-(.+)$', old)
    return f'{newprefix}-2026-{m.group(1)}' if m else old

def dedupe_examples(cond):
    # Clean common duplicate/partial examples left by the first pass.
    cond=cond.replace(' and Lewis v. City,',' ,').replace('Kogan v. Martin\'','Kogan v. Martin')
    cond=cond.replace('The expert\'s expert submission','The expert\'s submission')
    cond=cond.replace('a expert submission','an expert submission')
    cond=cond.replace('a appellate brief','an appellate brief')
    cond=cond.replace('one citation defect involving defective legal authorities','one citation defect involving nonexistent or incorrect case law')
    # remove duplicated adjacent examples like X and X
    cond=re.sub(r'\b([^,;]{8,80}) and \1\b', r'\1', cond)
    cond=cond.replace(', involving', ' involving') if 'including' not in cond else cond
    return sentence(cond)

def actor_from_cond(cond):
    low=cond.lower()
    if low.startswith('counsel') or "counsel's" in low or 'defense counsel' in low: return 'counsel'
    if 'expert' in low: return 'an expert'
    return 'a self-represented party'

def make_summary(row, idx):
    court=short_court(row['court']); date=row['date_filed']; case=row['case_name']
    cond=row['incident']['conduct'].rstrip('.')
    disp=re.sub(r'^The court\s+','',row['disposition'].rstrip('.'),flags=re.I)
    # Use caption for specificity, then shrink only if necessary.
    s=f"{court} on {date} in {case} found {cond[0].lower()+cond[1:]}. The court {disp}."
    if len(s.split())>60:
        s=f"{court} on {date} found {cond[0].lower()+cond[1:]}. The court {disp}."
    if len(s.split())>60:
        cond_short=textwrap.shorten(cond[0].lower()+cond[1:], width=170, placeholder='...')
        s=f"{court} on {date} found {cond_short}. The court {disp}."
    if len(s.split())<40:
        who=actor_from_cond(cond)
        s=f"{court} on {date} in {case} found defective authorities filed by {who}: {cond[0].lower()+cond[1:]}. The court {disp}."
    if len(s.split())>60:
        # Last resort: remove caption but keep exact order and conduct type.
        cond_short=textwrap.shorten(cond[0].lower()+cond[1:], width=155, placeholder='...')
        s=f"{court} on {date} found {cond_short}. The court {disp}."
    return sentence(s)

seen=set()
for row,idx in zip(rows,idx_for):
    if idx in COURT_FIX:
        court,code,level,state,prefix=COURT_FIX[idx]
        row['court']=court; row['court_code']=code; row['court_level']=level; row['state']=state
        row['decision_id']=prefix_id(row['decision_id'], prefix)
    if idx in DISP: row['disposition']=DISP[idx]
    if idx in COND: row['incident']['conduct']=COND[idx]
    row['incident']['conduct']=dedupe_examples(row['incident']['conduct'])
    if row['incident'].get('monetary_penalty') is not None and not row['incident'].get('currency'):
        row['incident']['currency']='USD'
    row['summary']=make_summary(row,idx)
    base=row['decision_id']; n=2
    while row['decision_id'] in seen:
        row['decision_id']=f"{base[:86]}-{n}"; n+=1
    seen.add(row['decision_id'])

Path('work/agents/decisions-t1-s6.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+"\n" for r in rows),encoding='utf-8')
print(f'polished {len(rows)} rows')
